# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# Azure DevOps yaml script tbv build een deploy een 
# python3 script die gebruik maakt van modules die eerst met pip geinstalleerd moeten worden.

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x' 

- script:
    'python -m pip install --upgrade pip'
  displayName: 'Install tools'

- script: 
    'pip install matplotlib'
  displayName: 'Install python modules'

# run het python script
- script:
    'python ./vb_mathplotlib_subplots_py3.py'
  displayName: 'run Python $(python.version)'
